from arvore import Arvore

arvore = Arvore()

arvore.insere(61)
arvore.insere(43)
arvore.insere(89)
arvore.insere(16)
arvore.insere(51)
arvore.insere(66)
arvore.insere(100)
arvore.insere(11)
arvore.insere(32)
arvore.insere(55)
arvore.insere(79)
arvore.insere(90)
arvore.insere(77)

print("Imprimindo em pre-ordem:")
arvore.imprimir_pre_ordem(arvore.raiz)
print("Imprimindo em intra-ordem:")
arvore.imprimir_intra_ordem(arvore.raiz)
print("Imprimindo em pos-ordem:")
arvore.imprimir_pos_ordem(arvore.raiz)

print("removendo folha:")
arvore.remove(11)
arvore.imprimir_pre_ordem(arvore.raiz)
print("removendo com filho a direita:")
arvore.remove(66)
arvore.imprimir_pre_ordem(arvore.raiz)
print("removendo filho a esquerda:")
arvore.remove(100)
arvore.imprimir_pre_ordem(arvore.raiz)
print("removendo raiz:")
arvore.remove(61)
arvore.imprimir_pre_ordem(arvore.raiz)